##### Load Data

In [35]:
import pandas as pd
df= pd.read_csv('delaney_solubility_with_descriptors.csv')

In [36]:
df.head(5)

   MolLogP    MolWt  NumRotatableBonds  AromaticProportion  logS
0   2.5954  167.850                0.0                 0.0 -2.18
1   2.3765  133.405                0.0                 0.0 -2.00
2   2.5938  167.850                1.0                 0.0 -1.74
3   2.0289  133.405                1.0                 0.0 -1.48
4   2.9189  187.375                1.0                 0.0 -3.04

##### Data Preparation

Data separation as x and y

In [37]:
y= df['logS']
y

0      -2.180
1      -2.000
2      -1.740
3      -1.480
4      -3.040
        ...
1139    1.144
1140   -4.925
1141   -3.893
1142   -3.790
1143   -2.581
Name: logS, Length: 1144, dtype: float64

In [38]:
x=df.drop('logS',axis=1)
x

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion
0     2.59540  167.850                0.0            0.000000
1     2.37650  133.405                0.0            0.000000
2     2.59380  167.850                1.0            0.000000
3     2.02890  133.405                1.0            0.000000
4     2.91890  187.375                1.0            0.000000
...       ...      ...                ...                 ...
1139  1.98820  287.343                8.0            0.000000
1140  3.42130  286.114                2.0            0.333333
1141  3.60960  308.333                4.0            0.695652
1142  2.56214  354.815                3.0            0.521739
1143  2.02164  179.219                1.0            0.461538

[1144 rows x 4 columns]

Data Splitting

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2, random_state=100)

In [40]:
x_train

     MolLogP    MolWt  NumRotatableBonds  AromaticProportion
107  3.14280  112.216                5.0            0.000000
378 -2.07850  142.070                0.0            0.000000
529 -0.47730  168.152                0.0            0.000000
546 -0.86740  154.125                0.0            0.000000
320  1.62150  100.161                2.0            0.000000
..       ...      ...                ...                 ...
802  3.00254  250.301                1.0            0.842105
53   2.13860   82.146                3.0            0.000000
350  5.76304  256.348                0.0            0.900000
79   3.89960  186.339               10.0            0.000000
792  2.52334  310.297                3.0            0.300000

[915 rows x 4 columns]

In [41]:
x_test

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion
822   2.91000  172.268                7.0            0.000000
118   7.27400  360.882                1.0            0.666667
347   1.94040  145.161                0.0            0.909091
1123  1.98640  119.378                0.0            0.000000
924   1.70062  108.140                0.0            0.750000
...       ...      ...                ...                 ...
1114  1.76210  478.513                4.0            0.000000
427   6.32820  276.338                0.0            1.000000
711   0.04430  218.205                5.0            0.000000
4     2.91890  187.375                1.0            0.000000
948   3.56010  318.328                2.0            0.750000

[229 rows x 4 columns]

##### Model Building

### Model Building with Cross-Validation
We will evaluate Linear Regression, Random Forest, and Gradient Boosting.

In [ ]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(max_depth=10, n_estimators=100, random_state=100),
    "Gradient Boosting": GradientBoostingRegressor(n_estimators=100, random_state=100),
}

kf = KFold(n_splits=5, shuffle=True, random_state=100)

### Evaluate Models

In [ ]:
import pandas as pd

results = []

for name, model in models.items():
    print(f"Training {name}...")
    
    # Cross validation
    cv_scores = cross_val_score(model, x_train, y_train, cv=kf, scoring='r2')
    cv_mean = np.mean(cv_scores)
    
    # Train on full train set
    model.fit(x_train, y_train)
    
    # Predict
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)
    
    # Metrics
    train_mse = mean_squared_error(y_train, y_train_pred)
    train_r2 = r2_score(y_train, y_train_pred)
    test_mse = mean_squared_error(y_test, y_test_pred)
    test_r2 = r2_score(y_test, y_test_pred)
    
    results.append({
        'Model': name,
        'CV R2': cv_mean,
        'Training MSE': train_mse,
        'Training R2': train_r2,
        'Test MSE': test_mse,
        'Test R2': test_r2
    })

results_df = pd.DataFrame(results)

### Model Comparison Results

In [ ]:
results_df.sort_values(by='Test R2', ascending=False)